version: 2
jobs:
  build:
    parallelism: 2

    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: github-slack_integration_test

    steps:
      - checkout

      - run: sudo apt install -y postgresql-client || true

      - restore_cache:
          keys:
            - bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: decrypt config/secrets.yml.enc
          command: bundle exec rake yaml_vault:decrypt

      - run:
          name: Setup DB
          command: bundle exec rake db:create db:migrate

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
